# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: github.com_keerthi-battula
    name: keerthi_battula/practiceMaven
trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- checkout: self
- checkout: MyGitHubRepo
